/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * LilDiscord Api
 * websocket chats
 * OpenAPI spec version: 1.0
 */
import { customInstance } from './axios.instance';
export type GetPodchannelsParams = {
/**
 * ID of the podchannel
 */
channelId: number;
};

export type GetPodchannelMessageParams = {
/**
 * podchannel id
 */
podchannel_id: number;
/**
 * limit
 */
limit: number;
/**
 * page
 */
page: number;
};

export type CreatePodchannelParams = {
/**
 * Name of the podchannel
 */
name: string;
/**
 * type of the podchannel
 */
types: string;
/**
 * channel of the podchannel
 */
id: number;
};

export type CreateChannelParams = {
/**
 * Name of Channel
 */
name?: string;
};

export type GetChannelParams = {
/**
 * ID of the channel
 */
id: string;
};

export interface QueriesPodchannel {
  channel_id?: number;
  created_at?: string;
  id?: number;
  name?: string;
  types?: string;
  updated_at?: string;
}

export interface QueriesMessage {
  author_id?: string;
  created_at?: string;
  id?: number;
  message?: string;
  podchannel_id?: number;
  updated_at?: string;
}

export interface QueriesChannel {
  created_at?: string;
  id?: number;
  name?: string;
  updated_at?: string;
}

export interface HandlerChannelWithPodchannels {
  channel?: QueriesChannel;
  podchannels?: QueriesPodchannel[];
}




type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];


  /**
 * Get one channel
 * @summary Get one channel
 */
export const getChannel = (
    params: GetChannelParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<HandlerChannelWithPodchannels>(
      {url: `/channel`, method: 'GET',
        params
    },
      options);
    }
  
/**
 * Create Channel
 * @summary Create Channel
 */
export const createChannel = (
    params?: CreateChannelParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<QueriesChannel>(
      {url: `/channel/create`, method: 'POST',
        params
    },
      options);
    }
  
/**
 * Get channels
 * @summary Get channels
 */
export const getChannels = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<QueriesChannel[]>(
      {url: `/channels`, method: 'GET'
    },
      options);
    }
  
/**
 * Create one podchannel
 * @summary Create one podchannel
 */
export const createPodchannel = (
    params: CreatePodchannelParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<HandlerChannelWithPodchannels>(
      {url: `/podchannel/create`, method: 'POST',
        params
    },
      options);
    }
  
/**
 * mess podchannel
 * @summary Get Messages PodChannel
 */
export const getPodchannelMessage = (
    params: GetPodchannelMessageParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<QueriesMessage[]>(
      {url: `/podchannel/message`, method: 'GET',
        params
    },
      options);
    }
  
/**
 * Get podchannels
 * @summary Get podchannels
 */
export const getPodchannels = (
    params: GetPodchannelsParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<QueriesPodchannel[]>(
      {url: `/podchannels`, method: 'GET',
        params
    },
      options);
    }
  
export type GetChannelResult = NonNullable<Awaited<ReturnType<typeof getChannel>>>
export type CreateChannelResult = NonNullable<Awaited<ReturnType<typeof createChannel>>>
export type GetChannelsResult = NonNullable<Awaited<ReturnType<typeof getChannels>>>
export type CreatePodchannelResult = NonNullable<Awaited<ReturnType<typeof createPodchannel>>>
export type GetPodchannelMessageResult = NonNullable<Awaited<ReturnType<typeof getPodchannelMessage>>>
export type GetPodchannelsResult = NonNullable<Awaited<ReturnType<typeof getPodchannels>>>
